@startuml
start
:首先发一份面试通知，直接确定5天的限期；
这样可以催促下前来面试者，提高时间利用率；
当然有的培训机构没有确定明确的期限，只是短信上写诚邀你届时面试;

if(是否面试) then (yes)

: 面试首先做个自我介绍、询问基本情况后、hr会向你简述公司大致情况；
以非本科生或是没有经验为由，先试听几天课，又招转培；
外包只是个幌子，主要目的还是拉人培训，送钱的当然是好苗子了，他们没有谁会跟钱过不去;

: 之后会有个面容姣好的女性讲师讲些简单的内容例如：html、css；内容容易接受（她都讲了n年重复的内容，能不好吗？），讲师外貌很好,教学质量也很高（实际上同一个内容讲了千遍万遍了），自然就不会有人离开了;

: 不知名的某某学院出来的经包装过的讲师照本宣科，重复某一课时模块讲解；
重复万遍事物都处理不好，要么无所谓，要么很低级，或者两者都有；
一般来说都是讲师都是无所谓很低级的，拿着工资混日子的;

: 知识讲解及实践操作蜻蜓点水，这当然录制的内容自然高不到哪去，学习效率是很低下的，就那不知道从那个网上抄来的做成的题库，实在没什么太多含金量可言的。;

: 学历作假、经验作假套路进公司（那些公司并不是傻子，只能说明这个手法很low），
所谓合作过的公司很多都是小型的房贷、股票等乱七八糟的公司以及少数同类教育（培训）公司;

: 如果被推荐去上述公司，不久被开除，肯定是怪你，当然进入这种类型的公司对自身技能方面没什么发展可言的;

stop

else (no)
: 不管笔试过没过，hr都会让你贷款培训，只是手段不一样；
如果笔试过了，就会以学历低下以及没经验的理由让诱使你培训（语气和善）；
如果笔试没过，就会以说明利害（疯狂打击你的自信心）的方式让你贷款培训后包配为由等着羊入虎口;

: 这期间，hr看到你沮丧的样子，会立即提议（装作很自然的样子）让你签培训贷款协议;当然，如果你打算去别的公司，
他还会“挽留”你说类似这样的话：你走后， 会是其他公司的项目经理来面试你，你还是过不了，还找不到就回来这 ”;


stop
@enduml