@startuml
start

: 有的培训公司会打球吐小球的滚雪球，知道自己公司已恶名昭彰了，但可以换成子公司的名称或伪装成外包等之类的公司重复此流程继续拉人头，美其名曰：人才与技术外包；
内地的省会或是几个较大的城市经济发展，培训机构贡献占比也不少，例如：广西北海衙门来说睁一只眼闭一只眼一带默认是传销的;

: 小插曲：
为什么培训机构热衷于搞网络课堂教学呢？
* 节省经费，人力物力等，每个地方都请个讲师开销太大，硬件也是如此，如果升级硬件整体的开销将会累加上升很多，谁都愿低成本、多赚钱
* 总有几个拉的出手的讲师讲些的新人感兴趣的精彩内容又故意模糊细节，以此来吸引学员
* 方便控制，房主、房管的权限是很大的

为什么有的培训机构会流露出大量视频呢，而有的却没有？（这里以培训机构视角考虑）
流露大量视频原因：
* 流露出大量视频是为了证明教学质量，得到反馈以此改善教学质量
* 扩大宣传范围以此提升品牌知名度
* 让更多的人来此品牌培训机构进行有偿培训

没有视频或者只有少量视频的原因：
* 害怕露底细（坑蒙拐骗的教学质量确实低得致命，倒是反将了一军想将视频发到网上的学员，因为质量比它高的确实不少...）
* 法律威胁侵权（非主要原因，很次要的因素）
* 面授（相对来说，应该不是很多）

在大专学历遍地走的时代，培训机构为什么还要验证下学历呢？
* 装逼，假装一个正经公司的流程，提升档次
* 培训机构也是为了防止一些虽未毕业但想试水接触社会（套路）的学生

只是拿一个就业证明和补习功课实在没必要来培训机构
* 就业证明不是吗，一个章印在湘潭火车站附近的招待所不远处就有刻的...（请理解我真正的意思）
* 没必要花万元补习功课什么的，连自己还被卖了都不知道吧
;

: xx开发实习生居多，大专学历或不限，从事经验不限以及人数不限(若干)，
或是空位较多5-10人以上（数字只是估计值），通常的招聘条件很模糊，
可以说是零门槛非专业生也能干的事，例如：
* 喜欢计算机相关专业，有强烈意愿在IT互联网上发展
* 工作认真、细致、敬业、责任心强、有较好学习能力者
* 熟练使用计算机基本操作;

:首先发一份面试通知，直接确定5天的限期；
这样可以催促下前来面试者，提高时间利用率；
当然有的培训机构没有确定明确的期限，只是短信上写诚邀你届时面试;

if(是否面试) then (yes)

: 面试首先做个自我介绍、询问基本情况后、hr会向你简述公司大致情况；
以非本科生或是没有经验为由，故意对贷款培训遮遮掩掩说：“
公司不是请人白干活的，设备维护，新人上手入职都是需要成本的，
而且我们只招好苗子进来，这当然需要自己支付一定费用，签下合同入职后每个月交上一千多来块钱就可以了”（其实就是贷款吸血）；
有的是先交三百左右不等的费用试听几天课，（一般来说他们是不会一开始说培训费数额的，怕把人吓跑了，近两万或两万以上左右，随着经济的发展这一数额会应该会更高），
然后招转培；外包只是个幌子，主要目的还是拉人培训，送钱的当然是好苗子了，他们没有谁会跟钱过不去;

: 之后会有个面容姣好的女性讲师讲些简单的内容例如：html、css；
这样的内容通常容易上手也很好教（她估计都讲了n年重复的内容，能不好吗？），看起来讲师外貌很好,教学质量也很高（实际上同一个内容讲了千遍万遍了，估计她都讲吐了），
自然就不会有人离开了;

: 这上课期间hr时不时的找你催促你签下贷款协议（他们提成也多啊），如上所述授课内容“通俗易懂”的讲师，你觉得这个讲师还不错什么的，他们再把培训贷款数额提出来;

: 贷款完正式开始上课前，先上一堂在此培训机构的成功就业人士（演员）的采访视频，以及浮夸公司雄伟的一面，还有不知道多少年的录制hr关于讲解职场的视频，看来定期对学员“洗脑”教育拉人头没差了;

: 这是他们会推荐拉一个人减免学费什么的
（你想想，这么做你把好朋友给卖了，“赚到”这千来块钱，而培训机构赚了万来块，而后朋友的仇恨又转移到你身上究竟是你赚了还是你亏了呢？）;

: 不知名的某某学院出来的经包装过的讲师照本宣科，重复某一课时模块讲解；
重复万遍事物都处理不好，要么无所谓，要么很低级，或者两者都有；
一般来说都是讲师都是无所谓很低级的，拿着工资混日子的;

: 知识讲解及实践操作蜻蜓点水，这当然录制的内容自然高不到哪去，学习效率是很低下的，就那不知道从那个网上抄来的做成的题库，实在没什么太多含金量可言的。
所谓的项目课也是残缺不全敷衍了事，因为他们自己都可能不懂;

else (no)
: 不管笔试过没过，hr都会让你贷款培训，只是手段不一样；
如果笔试过了，就会以学历低下以及没经验的理由让诱使你培训（语气和善）；
如果笔试没过，就会以说明利害（疯狂打击你的自信心）的方式让你贷款培训后包配为由等着羊入虎口（钱出了，他们给“安排”一个岗位再把你辞了就是你自己的事了）;

: 这期间，hr看到你沮丧的样子，会立即提议（装作很自然的样子）让你签培训贷款协议;当然，如果你打算去别的公司，
他还会“挽留”你说类似这样的话：你走后， 会是其他公司的项目经理来面试你，你还是过不了，还找不到就回来这 ”;

: 当然如果你入套就和面试入套之后的流程差不多了，仅仅只是大同小异而已;

stop


if(是否进行人才租赁（中介的形式）) then (yes)

: 跟在任职的公司没有任何关系，任职的公司只是与中介签订人才租赁协议一次性付款给中介，你签订协议地点也不是所任职的公司而是中介，工资由中介发放的。
如此一来自然没有五险一金可言了，解雇自然也没有工资什么的了，说白了就是为培训机构打工的临时工
（贷款还欠着它的钱，然后呢，出来工作又被培训机构抽了血汗钱）;

else (no)

: 学历作假、经验作假套路进公司（那些公司并不是傻子，只能说明这个手法很low），
所谓合作过的公司很多都是小型的房贷、股票等乱七八糟的公司以及少数同类教育（培训）公司;

: 如果被推荐去上述公司，不久被开除，肯定是怪你，当然进入这种类型的公司对自身技能方面没什么发展可言的;

stop

@enduml
