@startuml
: 如果向花呗借3k，假定每月还500，也就是6个月将3k还完；目前花呗每月的利息是0.05%，也就是每月需要还150的利息，6个月还完3k的利息是900；
500+150 每月实际偿还3k与3k每月0.05%（百分比随着逾过期限延长而增涨）利息的总和；特别是电子商品贬值也是非常快的，就算6个月贬值500块吧：
到还完3k的借贷，3.9k买了一个价值2.5k的商品（这还不算卖家对此商品的虚高标价，如果此商品实际仅值2.5k而买3k呢？那不很血亏吗？）；
实际上为了即时入手使用此贬值很快的产品而多支出了1.4k，这一金额随着预期偿还而增长，即使偿还完3k（店家的商品），但3k的利息还是没还完（花呗）；
这相当于当时（只不过当时没有购买能力或不想一次性结账罢了）3.9k买了3k产品，其实等这些等一段时间就好了，没必要花上额外的开支及时间购买过时（贬值）的产品;
: 在用户购买商品时，淘宝用红包优惠的减免信息诱使用户使用花呗（自家的借贷软件）；
例如：价值365的商品，利用花呗减免200，再加上红包的10块优惠，这样就只需要支付155，下个月还上免息;

@enduml


' 目前花呗每月的利息是0.05%，也就是每月需要还150的利息，无形中每月是要交上650，6个

' 借款的本质就是使超出购买支出的预算被借贷人当作当前的购买支出，而忽略实际复杂环境做出的理想偿还决策（往往这些理想决策，总会超出预期）