@startuml
start
:在路边发放免费充电宝，“您好，我这里有个移动周年优惠活动，填下单子给您免费送个充电宝”;
:顾客答：“不要再交话费什么的了吗？”;
:"不用，您只要填写这个单子就行了";
if (进店填写单子？)  then (yes)
: 一项普通民意调查单;
: 一项“内部人员不得参与” 字样的优惠单;
: 两项单子填写完成后，参与抽奖100%必中1k积分;
: 这时发放宣传单说：“你看下，需交550-1000元兑换手机或送电脑，再者或是交99元送平板，注意选好了就不能更换礼品了”;
if (是否选择交钱购买手机或是电脑) then (yes)
: 交钱后，打印单子对着顾客说：这个需要交3k块钱话费再送你平板;
: 这3k话费你可以选择共享话费（移动的钱套钱的策略），个人就只能自己用，分期也可以两年交3k也是可以的（故意忽略还款利息）;
: 如果执意需要说利息费用多少才告诉顾客200/3000 的一月多少百分比（0.0666...%）收取利息;
: 顾客想退单的时候就说：“签好了就不能随意退单，退单很麻烦的，你看是一次性付款还是分期（贷款），不懂的跟我说，我帮你解决”;
: 顾客：主要集中在贷款没明白
: 导购员：分期的话，下个月的这一天你的话费将有3k自动打在你卡上，但你需要每个月交200块钱话费，
你想想一月200块话费，1年半载不就还完了吗，六年的使用完3k话费期限，难道还不够吗？（故意忽略还款利息）
* 你花3k（忽略分期），一个2.7k的平板（网上只需1.4k），3k的话费（3k的话费，如果需要按时换上等于还是没有充值一样）是不是很值;
: 每个月扣200块分期利息，1.5年左右，15x200=3000（贷款偿还完毕）；每月交200话费，1.5年左右，15x200=3000（花费偿还完毕）；
这意味着将要充值巨额的话费，以及每月200块利息（电子产品的掉价，上交话费与分期利息，这些都很不值）;
if (是否态度强硬退掉购买的“礼品”（手机或电脑）？) then (yes)
    : 推三阻四的让你继续签分期（懂点水的会让你勉强退单），这时出店报警、告消协;
else (no)
    : 已经落入分期陷阱;
endif
else (no)
: “真的不去店里看下吗，这充电宝还有其他礼品都是免费送的”;
endif 
while (进入店里看看?) is (yes)
    : 已经进入如上“进店填写单子” 诱导分期付款流程陷阱;
endwhile (no) 
    : 对“优惠礼品”不感兴趣，没有中欺诈陷阱;
endif
stop
@enduml